let userName = 'John';
let tamplateString = `Hello, ${userName}`;
console.log(tamplateString);
console.log(tamplateString.length);
let text = 'Привіт, світ!';
console.log(text.length);
console.log(text.charAt(0));
console.log(text.charAt(text.length - 1));
console.log(text.includes('світ'));
console.log(text.indexOf('Cвіт'));
console.log(text.indexOf('світ'));
console.log(text.toUpperCase());
console.log(text.toLowerCase());
let text1 = '   hjgrjhgier   ';
console.log(text1.trim());
let greeting = 'Привіт';
let place = 'світ';
let message = greeting + ', ' + place + '!';
console.log(message);
